In [23]:
import pandas as pd

players = pd.read_csv('../data/processed/players.csv')
fixtures = pd.read_csv("../data/processed/fixtures.csv")

In [24]:
players

,id,first_name,second_name,element_type,now_cost,minutes,total_points
0,1,David,Raya Martín,1,60,1530,75
1,2,Kepa,Arrizabalaga Revuelta,1,41,0,0
2,3,Karl,Hein,1,40,0,0
3,4,Tommy,Setford,1,39,0,0
4,5,Gabriel,dos Santos Magalhães,2,62,990,81
...,...,...,...,...,...,...,...
765,709,Ladislav,Krejcí,2,45,1053,22
766,720,Tolu,Arokodare,4,54,335,21
767,749,Mateus,Mané,4,45,91,9
768,766,Saheed,Olagunju,2,40,0,0
769,767,Luke,Rawlings,3,45,0,0

In [28]:
top_players = players.sort_values("total_points", ascending=False).head(10)
top_players[["first_name", "total_points", "element_type"]]

    first_name  total_points  element_type
485     Erling           151             4
138    Antoine            99             3
511      Bruno            99             3
19      Declan            97             3
252     Trevoh            94             2
288       Marc            93             2
471       Phil            91             3
51      Morgan            91             3
284     Daniel            89             2
7      Jurriën            86             2

In [25]:
fixtures

,id,event,team_h,team_a,team_h_difficulty,team_a_difficulty,kickoff_time
0,1,1,12,4,3,4,2025-08-15T19:00:00Z
1,2,1,2,15,3,3,2025-08-16T11:30:00Z
2,3,1,6,10,2,3,2025-08-16T14:00:00Z
3,6,1,18,3,2,3,2025-08-16T14:00:00Z
4,5,1,17,19,2,3,2025-08-16T14:00:00Z
...,...,...,...,...,...,...,...
375,376,38,13,2,3,4,2026-05-24T15:00:00Z
376,377,38,16,4,3,3,2026-05-24T15:00:00Z
377,379,38,18,9,2,3,2026-05-24T15:00:00Z
378,378,38,17,7,3,3,2026-05-24T15:00:00Z
379,380,38,19,11,2,2,2026-05-24T15:00:00Z